### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by FrankHossfeld**
* fixed: issue with artifactid
There were several places where the artifactid 'patternfly-gwt' was used. Changed to 'patternfly-java`.

* update Nalu version 2.0.0-rc-3
Updated to latest Nalu version

### CODE REVIEW

**Comment by hpehl** [comment]
Thanks @FrankHossfeld for the contribution!

**Comment by hpehl** [comment]
I made some modification to your PR. I'd like to give some feedback about the motivations:

- In general I try to follow the KISS principle. 
- I use factory methods, if there are lots of different ways to create a component (more than 3 or 4) or if there are fundamental differences between variations of a component (like embedded or toast alert group). Otherwise I like to stick with normal constructors. 
- I'm a big fan of fluent APIs. That's why most of the modification  methods return the component instance. 

If you have a different point of view, please let me know. I'm happy to discuss the design choices.

**Comment by FrankHossfeld** [comment]
> In general I try to follow the KISS principle.

Agree

> I use factory methods, if there are lots of different ways to create a component (more than 3 or 4) > or if there are fundamental differences between variations of a component (like embedded or 
> toast alert group). Otherwise I like to stick with normal constructors.

Ok, that was unclear. 

> I'm a big fan of fluent APIs. That's why most of the modification methods return the component instance.

me too.

Will check your changes.

**Comment by FrankHossfeld** [comment]
Can you share the code style settings for this project?

**Comment by hpehl** [comment]
Code style settings are now available as per https://github.com/hpehl/patternfly-java/commit/dba440a0b628bd924da556712ccaf133d05ed40b. 

It follows the setup used in Quarkus: https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#ide-config-and-code-style

**Pull request merged**
